version: "3.7"
services:
  devradar-backend:
    build: ./backend
    container_name: "devradar-backend"
    volumes:
      - ./backend:/usr/backend/code
    ports:
      - 3333:3000
    networks:
      - devradar_network
networks:
  devradar_network:
    driver: bridge
