# Docker build para o backend node
FROM node:alpine

WORKDIR /usr/backend
COPY ./backend/package*.json ./
RUN npm install --silent
RUN ln -sf ./code/package.json ./ && ln -sf ./code/package-lock.json ./

CMD ["npm", "run", "start.dev"]