version: "3.7"
services:
  omnistack-10-backend:
    build: ./
    #command: npm run start
    container_name: "omnistack-10-backend"
    volumes:
      - .:/usr/backend/code
      #- omnistack_10_data:/usr/backend/node_modules
      #- .:/usr/backend
      #  - /usr/backend/node_modules/* # Remove this if you have pure JS dependencies
    ports:
      - 3000:3000
#     networks:
#       - omnistack_10_network
#volumes:
#   omnistack_10_data: {}
# networks:
#   omnistack_10_network:
#     driver: bridge